/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as CommercialMitigationRouteImport } from './routes/commercial-mitigation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as NewConstructionRouteImport } from './routes/new-construction'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RadonTestingRouteImport } from './routes/radon-testing'
import { Route as RealEstateServicesRouteImport } from './routes/real-estate-services'
import { Route as ResidentialMitigationRouteImport } from './routes/residential-mitigation'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas.index'
import { Route as ServiceAreasCityRouteImport } from './routes/service-areas.$city'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesRadonMitigationRouteImport } from './routes/services.radon-mitigation'
import { Route as ServicesRadonTestingRouteImport } from './routes/services.radon-testing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialMitigationRoute = CommercialMitigationRouteImport.update({
  id: '/commercial-mitigation',
  path: '/commercial-mitigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const NewConstructionRoute = NewConstructionRouteImport.update({
  id: '/new-construction',
  path: '/new-construction',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RadonTestingRoute = RadonTestingRouteImport.update({
  id: '/radon-testing',
  path: '/radon-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateServicesRoute = RealEstateServicesRouteImport.update({
  id: '/real-estate-services',
  path: '/real-estate-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentialMitigationRoute = ResidentialMitigationRouteImport.update({
  id: '/residential-mitigation',
  path: '/residential-mitigation',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/service-areas/',
  path: '/service-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasCityRoute = ServiceAreasCityRouteImport.update({
  id: '/service-areas/$city',
  path: '/service-areas/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRadonMitigationRoute = ServicesRadonMitigationRouteImport.update({
  id: '/services/radon-mitigation',
  path: '/services/radon-mitigation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRadonTestingRoute = ServicesRadonTestingRouteImport.update({
  id: '/services/radon-testing',
  path: '/services/radon-testing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/commercial-mitigation': typeof CommercialMitigationRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/new-construction': typeof NewConstructionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/radon-testing': typeof RadonTestingRoute
  '/real-estate-services': typeof RealEstateServicesRoute
  '/residential-mitigation': typeof ResidentialMitigationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/services/radon-mitigation': typeof ServicesRadonMitigationRoute
  '/services/radon-testing': typeof ServicesRadonTestingRoute
  '/blog/': typeof BlogIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/commercial-mitigation': typeof CommercialMitigationRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/new-construction': typeof NewConstructionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/radon-testing': typeof RadonTestingRoute
  '/real-estate-services': typeof RealEstateServicesRoute
  '/residential-mitigation': typeof ResidentialMitigationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/services/radon-mitigation': typeof ServicesRadonMitigationRoute
  '/services/radon-testing': typeof ServicesRadonTestingRoute
  '/blog': typeof BlogIndexRoute
  '/service-areas': typeof ServiceAreasIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/commercial-mitigation': typeof CommercialMitigationRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/new-construction': typeof NewConstructionRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/radon-testing': typeof RadonTestingRoute
  '/real-estate-services': typeof RealEstateServicesRoute
  '/residential-mitigation': typeof ResidentialMitigationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/services/radon-mitigation': typeof ServicesRadonMitigationRoute
  '/services/radon-testing': typeof ServicesRadonTestingRoute
  '/blog/': typeof BlogIndexRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/commercial-mitigation'
    | '/contact'
    | '/faqs'
    | '/new-construction'
    | '/privacy-policy'
    | '/radon-testing'
    | '/real-estate-services'
    | '/residential-mitigation'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/service-areas/$city'
    | '/services/radon-mitigation'
    | '/services/radon-testing'
    | '/blog/'
    | '/service-areas/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/commercial-mitigation'
    | '/contact'
    | '/faqs'
    | '/new-construction'
    | '/privacy-policy'
    | '/radon-testing'
    | '/real-estate-services'
    | '/residential-mitigation'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/service-areas/$city'
    | '/services/radon-mitigation'
    | '/services/radon-testing'
    | '/blog'
    | '/service-areas'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/commercial-mitigation'
    | '/contact'
    | '/faqs'
    | '/new-construction'
    | '/privacy-policy'
    | '/radon-testing'
    | '/real-estate-services'
    | '/residential-mitigation'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/service-areas/$city'
    | '/services/radon-mitigation'
    | '/services/radon-testing'
    | '/blog/'
    | '/service-areas/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CommercialMitigationRoute: typeof CommercialMitigationRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  NewConstructionRoute: typeof NewConstructionRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RadonTestingRoute: typeof RadonTestingRoute
  RealEstateServicesRoute: typeof RealEstateServicesRoute
  ResidentialMitigationRoute: typeof ResidentialMitigationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServiceAreasCityRoute: typeof ServiceAreasCityRoute
  ServicesRadonMitigationRoute: typeof ServicesRadonMitigationRoute
  ServicesRadonTestingRoute: typeof ServicesRadonTestingRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial-mitigation': {
      id: '/commercial-mitigation'
      path: '/commercial-mitigation'
      fullPath: '/commercial-mitigation'
      preLoaderRoute: typeof CommercialMitigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-construction': {
      id: '/new-construction'
      path: '/new-construction'
      fullPath: '/new-construction'
      preLoaderRoute: typeof NewConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radon-testing': {
      id: '/radon-testing'
      path: '/radon-testing'
      fullPath: '/radon-testing'
      preLoaderRoute: typeof RadonTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate-services': {
      id: '/real-estate-services'
      path: '/real-estate-services'
      fullPath: '/real-estate-services'
      preLoaderRoute: typeof RealEstateServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residential-mitigation': {
      id: '/residential-mitigation'
      path: '/residential-mitigation'
      fullPath: '/residential-mitigation'
      preLoaderRoute: typeof ResidentialMitigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/service-areas'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$city': {
      id: '/service-areas/$city'
      path: '/service-areas/$city'
      fullPath: '/service-areas/$city'
      preLoaderRoute: typeof ServiceAreasCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/radon-mitigation': {
      id: '/services/radon-mitigation'
      path: '/services/radon-mitigation'
      fullPath: '/services/radon-mitigation'
      preLoaderRoute: typeof ServicesRadonMitigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/radon-testing': {
      id: '/services/radon-testing'
      path: '/services/radon-testing'
      fullPath: '/services/radon-testing'
      preLoaderRoute: typeof ServicesRadonTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  CommercialMitigationRoute: CommercialMitigationRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  NewConstructionRoute: NewConstructionRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RadonTestingRoute: RadonTestingRoute,
  RealEstateServicesRoute: RealEstateServicesRoute,
  ResidentialMitigationRoute: ResidentialMitigationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServiceAreasCityRoute: ServiceAreasCityRoute,
  ServicesRadonMitigationRoute: ServicesRadonMitigationRoute,
  ServicesRadonTestingRoute: ServicesRadonTestingRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
